Check unprivileged user namespaces
edytuk/apptainer pull request #117
Opened 2022-07-01 15:35 UTC by edytuk

Fixes # 514

2022-07-01 17:11 UTC, DrDaveD requested changes

2022-07-01 17:11 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +	echo "enabled"
That's what I asked for but I think while we're at it let's also check here whether --with-suid or --without-suid has been passed, and if they have not then say
```
enabled.  Implying --without-suid

2022-07-01 17:11 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +	if echo "$cmdline" | grep -q -- "--with-suid\|--without-suid"; then
This is works and is OK but the alternative I was thinking of was to change $with_suid to be initialized to -1, check for that here, and then after the base checks change with_suid == -1 into with_suid=0. You can decide which you prefer.

2022-07-04 10:35 UTC, edytuk commented on mlocal/checks/basechecks.chk
> +	if echo "$cmdline" | grep -q -- "--with-suid\|--without-suid"; then
Is it ok to change with_suid in basecheck.chk or it is better to do it in mconfig file?

2022-07-04 14:47 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +	if echo "$cmdline" | grep -q -- "--with-suid\|--without-suid"; then
Either way is ok.  In this case since it will be saying "Implying --without-suid" here I think you might as well go ahead and set it here.

2022-07-06 15:02 UTC, DrDaveD approved these changes

2022-07-06 15:24 UTC, closed without merging