start of work to add DOCKER_HOST environment, from sylabs 875
edytuk/apptainer pull request #137
Opened 2022-08-17 12:39 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity# 875
 which fixed
- sylabs/singularity# 805
- sylabs/singularity# 878

2022-08-18 18:41 UTC, DrDaveD requested changes

2022-08-18 18:41 UTC, DrDaveD commented on pkg/cmdline/flag.go
> +				// This annotation just needs to be present, period
Between these two comment lines I believe if precedence > 0 it should continue.   If you don't do that, and somebody sets both DOCKER_HOST and SINGULARITY_DOCKER_HOST to different values you'll get a bogus warning about APPTAINER_DOCKER_HOST and SINGULARITY_DOCKER_HOST having different values (please verify that).  This function gets called twice, once with precedence 0 and once with precedence 1.  There's no need to process a prefix-less variable when precedence is 1 because it will have already been processed at precedence 0.   An additional comment before that check can be
```
// The prefix-less check only needs to be done for precedence 0
```

2022-08-24 11:08 UTC, edytuk commented on pkg/cmdline/flag.go
> +				// This annotation just needs to be present, period
You are right, if somebody sets both DOCKER_HOST and SINGULARITY_DOCKER_HOST to different values you will get a bogus warning about APPTAINER_DOCKER_HOST and SINGULARITY_DOCKER_HOST having different values. I made these [changes](https://github.com/edytuk/apptainer/compare/2b13ba769efd896b8ef8b259503163cda9ef229c..db537349bf0645142111cbdd5ceb35c0f2b859c9) in order to avoid this and also I stop processing a prefix-less variable when precedence is 1.

2022-08-24 23:06 UTC, DrDaveD commented on pkg/cmdline/flag.go
> +			if !withoutPrefix {
I'm not sure why setting withoutPrefix should exclude indicating that the key is found.  What's the explanation for that?

2022-08-25 09:56 UTC, edytuk commented on pkg/cmdline/flag.go
> +			if !withoutPrefix {
Otherwise there is a warning about APPTAINER_DOCKER_HOST and SINGULARITY_DOCKER_HOST having different values if somebody sets both DOCKER_HOST and SINGULARITY_DOCKER_HOST to different values. All flags without and with prefix APPTAINER are added to foundKeys and then these flags are compared with flag that has prefix SINGULARITY, so I stop including without prefix flags in order to not compare this value with flag that has SINGULARITY prefix.

2022-08-25 12:35 UTC, closed without merging