chore: refactor actions_linux.go / execStarter, from sylabs 1003
edytuk/apptainer pull request #170
Opened 2022-10-14 15:06 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity# 1003

The original PR description was:
> The execStarter function, which creates an EngineConfig defining how to run a container, and then executes the starter binary, is extremely long and complex. It accesses a lot of CLI flags directly, as global variables, and is generally hard to reason about, especially where it modifies those global vars in a way that changes behavior later.
> 
> The code shouldn't really be in the CLI layer. To handle execution of OCI images with an OCI native runtime we need to be able to separate the CLI from starter execution.
> 
> As a first step in refactoring to move this code out, this PR:
> 
> * Renames actions_linux.go to starter_linux.go to reflect the fact this code is all about calling the starter, and is not just for actions... it's used by instances too.
> 
> * Does some extraction of code into functions, to make execStarter itself easier to follow.
> 
> * Re-orders some code (where it is not order sensitive), to group like operations together (e.g. mount handling).
> 
> 
> Note that the starter execution is still tied to the global vars backing CLI flags, and modifies them. This is a first step of many :-)

2022-10-19 17:57 UTC, DrDaveD requested changes

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +func useSuid(uid uint32, engineConfig *apptainerConfig.EngineConfig) (useSuid, forceUserNs bool) {
Remove forceUserNs return code

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
>  	}
Remove the forceUserNs, it's not doing anything.

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +		// which is important to maintain security.
Remove this comment, it's not true anymore for us.

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +		env, err := interpreter.EvaluateEnv(content, args, currentEnv)
Let's keep this as envvars

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +	if err := setEnv(args, engineConfig, generator); err != nil {
Let's call this function setEnvVars instead of setEnv

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +// PrepareImage perfoms any image preparation required before execution.
Change perfoms to performs

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +	insideUserNs, _ := namespaces.IsInsideUserNamespace(os.Getpid())
Since this is set in 3 functions, instead set it in execStarter and pass it as a parameter to the 3 functions.

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +	loadOverlay := false
Set loadOverlay in exec starter and pass it as a parameter to the two functions that need it.

2022-10-19 17:57 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +
Set these in execStarter and pass cfg as parameter to the two functions.

2022-10-20 14:10 UTC, edytuk commented on cmd/internal/cli/starter_linux.go
> +		if (os.Getuid() == 0) && namespaces.IsUnprivileged() {
I also changed it in withPrivilege function.

2022-10-20 18:19 UTC, DrDaveD approved these changes
Good job

2022-10-20 19:47 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +		if (uid == 0) && namespaces.IsUnprivileged() {
Actually there is a problem here, I found by testing it.  The problem happens if you are doing sudo and using a `--security uid:N` option (with a suid installation because otherwise it completely fails).  In that case the fakeroot re-exec isn't noticed because the uid variable gets mapped and it goes into a loop.  So instead move this whole bit of code all the way to the beginning of execStarter.  Restore the lines before it
```
	uid := uint32(os.Getuid())
	gid := uint32(os.Getgid())
```
Then instead of looking up those values again inside of setTargetIDs, pass them in as parameters and change the `:=` into just `=` to reuse the same variables.

2022-10-21 15:15 UTC, edytuk commented on cmd/internal/cli/starter_linux.go
> +		if (uid == 0) && namespaces.IsUnprivileged() {
I made changes

2022-10-21 15:55 UTC, DrDaveD requested changes

2022-10-21 15:55 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +	err = setTargetIDs(uid, gid, engineConfig)
No, this still needs to return a potentially updated uid & gid.

2022-10-21 19:45 UTC, DrDaveD commented
Also please rebase on the current main, because I just merged a PR that modified actions_linux.go.

2022-10-24 17:45 UTC, DrDaveD requested changes

2022-10-24 17:45 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +func setTargetIDs(uid uint32, gid uint32, engineConfig *apptainerConfig.EngineConfig) (userID, groupID uint32, err error) {
Just one more little thing.  Let's not set names on the first two return codes here because they are not used.  Make it
```
(uint32, uint32, err error)
```

2022-10-25 09:06 UTC, edytuk commented on cmd/internal/cli/starter_linux.go
> +func setTargetIDs(uid uint32, gid uint32, engineConfig *apptainerConfig.EngineConfig) (userID, groupID uint32, err error) {
It seems that golangci-lint does not like it

2022-10-25 15:36 UTC, DrDaveD commented on cmd/internal/cli/starter_linux.go
> +func setTargetIDs(uid uint32, gid uint32, engineConfig *apptainerConfig.EngineConfig) (userID, groupID uint32, err error) {
Ok the problem is you can't mix named and unnamed return paramters.  So remove also the "err" and then define it with a ":=" the first time it is used.

2022-10-25 21:41 UTC, DrDaveD approved these changes
Be aware that a first-time contributor also has a pending PR touching actions_linux.go and it's likely his PR will get merged first, so after that you'll need to rebase again.

2022-10-26 09:02 UTC, closed without merging