rpm: fix: correct BuildRequires/Requires for SLES, from sylabs 1456
edytuk/apptainer pull request #268
Opened 2023-03-20 14:41 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity# 1456
 which fixed
- sylabs/singularity# 1453

The original PR description was:
> * On SLES we intend to require runc, not crun.
> * squashfs had a duplicate Requires, instead of a BuildRequires.

2023-03-20 16:37 UTC, DrDaveD requested changes

2023-03-20 16:37 UTC, DrDaveD commented on dist/rpm/apptainer.spec.in
> +BuildRequires: squashfs-tools
This is not a duplicate for us, it is just misplaced.  Delete these changes for this PR.

Separately, please create a PR against the main branch that moves this whole %if/%else down a little bit where our Requires are instead of BuildRequires.  You can say it was inspired by sylabs 1456, but there's no need to pull in a commit.

2023-03-20 16:37 UTC, DrDaveD commented on scripts/ci-rpm-build-test
> +yum install -y libseccomp-devel e2fsprogs cryptsetup squashfs-tools
Delete this change.  We don't need the package to build, we only need it at run time, and the later install of the built rpm with yum will pull it in.

2023-03-21 21:34 UTC, DrDaveD requested changes

2023-03-21 21:34 UTC, DrDaveD commented on dist/rpm/apptainer.spec.in
> +%endif
I would like this movement to be done in a separate PR against the main branch, not on the oci-action branch.

2023-03-22 21:25 UTC, DrDaveD requested changes
Now this removes the `Requires: squashfs` or `Requires: squashfs-tools` when it should be leaving it alone.  The only change that should be here (unless you want to cherry-pick the commit from main for squashfs) is to have it require runc on suse.

2023-03-23 11:07 UTC, edytuk commented
I removed this because those changes are already bellow https://github.com/edytuk/apptainer/pull/268/files#diff-07e9c9bb3b43a4675f3c083f54998f839808a190bb4844dbfdda91aa457682ebR103-R108

2023-03-23 14:03 UTC, DrDaveD commented
Oh.  I see.  That's an oci-action change only.

2023-03-23 14:03 UTC, DrDaveD approved these changes

2023-03-23 17:50 UTC, merged