add get login password command, from sylabs 1692
edytuk/apptainer pull request #294
Opened 2023-05-23 14:12 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity# 1692

The original PR description was:
> This PR adds a get login password command that allows users to retrieve the cli token from the currently logged in user.
> 
> This enables the workflow to pipe the cli secret directly into docker login flow from reading std-in. This workflow is recommended to prevent the password from ending up in a shell's history or log-files
> 
> Example usage: `singularity remote get-login-password | docker login --username foo --password-stdin`

2023-05-23 15:06 UTC, DrDaveD requested changes

2023-05-23 15:06 UTC, DrDaveD commented on CHANGELOG.md
> +  password from ending up in a shell's history or log-files.
Change these two sentences to
```
This enables piping the secret directly into docker login while preventing it from showing up
in a shell's history.
```

2023-05-23 15:06 UTC, DrDaveD commented on docs/remote.go
> +
I see no good reason for this blank line

2023-05-23 15:06 UTC, DrDaveD commented on docs/remote.go
> +	RemoteGetLoginPasswordLong    string = `The 'remote get-login-password' command allows you to retrieve the cli secret for the currently user.`
Change `currently` to `current`

2023-05-23 15:06 UTC, DrDaveD commented on docs/remote.go
> +	RemoteGetLoginPasswordExample string = `$ apptainer remote get-login-password | docker login -u user --password-stdin https://harbor.sylabs.io`
Delete `https://harbor.sylabs.io`  (it defaults to dockerhub).

2023-05-23 15:06 UTC, DrDaveD commented on internal/app/apptainer/remote_get_login_password.go
> +//
Delete empty comment

2023-05-23 15:06 UTC, DrDaveD commented on internal/app/apptainer/remote_get_login_password.go
> +//
Delete empty comment

2023-05-23 15:06 UTC, DrDaveD commented on internal/app/apptainer/remote_get_login_password_test.go
> +//
Delete empty comment

2023-05-23 15:06 UTC, DrDaveD commented on internal/app/apptainer/remote_get_login_password_test.go
> +//
Delete empty comment

2023-05-23 16:34 UTC, edytuk commented on internal/app/apptainer/remote_get_login_password.go
> +//
check_source test does not like that https://github.com/edytuk/apptainer/actions/runs/5059641930/jobs/9081471481

2023-05-23 19:20 UTC, DrDaveD commented on internal/app/apptainer/remote_get_login_password.go
> +//
Compare it to other source files in the same directory.  They do not have the blank comment.  It does look like they have fewer spaces on the indents the next few lines.

What happens when you run gofumpt -w on the file?

2023-05-24 11:55 UTC, edytuk commented on internal/app/apptainer/remote_get_login_password.go
> +//
I added these lines to the begging of file
```
// Copyright (c) Contributors to the Apptainer project, established as
//   Apptainer a Series of LF Projects LLC.
//   For website terms of use, trademark policy, privacy policy and other
//   project policies see https://lfprojects.org/policies
```
But gofumpt -w does this
```
// Copyright (c) Contributors to the Apptainer project, established as
//
//      Apptainer a Series of LF Projects LLC.
//      For website terms of use, trademark policy, privacy policy and other
//      project policies see https://lfprojects.org/policies
//
```
I do not know why it does that for these two new files, but it does not for other files

2023-05-24 16:27 UTC, closed without merging