ci: fix buildcfg check, and usage in bin.FindBin, from sylabs 1879
edytuk/apptainer pull request #355
Opened 2023-07-18 08:37 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity# 1879
 which fixed
- sylabs/singularity# 1823

The original PR description was:
> If code in `pkg/` uses `bin.FindBin` then prior to this PR it would attempt to import `buildcfg`.
> 
> `buildcfg` is only available as part of a full build of SingularityCE, not when other code imports `pkg/`.
> 
> Add build tag gated variants of the private functions called by `bin.FindBin` that do not require `buildcfg`, to avoid this issue.

2023-07-19 22:18 UTC, DrDaveD requested changes

2023-07-19 22:18 UTC, DrDaveD commented on internal/pkg/util/bin/bin_no_apptainer.go
> +func findOnPath(name string) (path string, err error) {
This code has apparently not been tested at all because the apptainer version of this function has an extra `bool` parameter (which can be ignored here but should be accepted).  

I think maybe that bin_test.go will work without the additional `//go:build apptainer_engine`, work with or without the tag.  Try it.  You should then be able to do `go test .` and `go test -tags apptainer_engine .` and in both cases have it run the test.

2023-07-20 12:21 UTC, edytuk commented on internal/pkg/util/bin/bin_no_apptainer.go
> +func findOnPath(name string) (path string, err error) {
I updated `findOnPath` function, removed `//go:build apptainer_engine` from `bin_test.go` and ran both `go test` commands, tests were running in both cases.

2023-07-20 19:38 UTC, DrDaveD approved these changes
With this PR can you re-enable the buildcfg in oci-action?

2023-07-21 12:23 UTC, edytuk commented
Once PR is merged in apptainer repository, I will rebase oci-action branch and I will re-enable the buildcfg.

2023-07-21 12:26 UTC, closed without merging