feat: Add --no-eval for OCI compatible argument and env var handling, from sylabs 704
edytuk/apptainer pull request #86
Opened 2022-05-05 13:14 UTC by edytuk

This pulls in sylabs PR

- sylabs/singularity#704
which fixed
- sylabs/singularity#487

The original PR description was:
> Address sylabs/singularity#487 by adding a `--no-eval` actions flag, which does the following:
> 
> 1. Quotes environment variable values in the `inject-singularity-env.sh` generated script using single quotes to
>        ensure the values are not evaluated when the injection script is sourced.
>        _This behavior applies to existing and newly created images._
> 
> 2. Uses an alternate path in the generated runscript for images built from OCI sources, that avoids evaluating CMD / ENTRYPOINT parts, and args in the shell.
>        _This behavior only applies to newly created images, that contain the new form of the generated OCI runscript._
> 
> 
> The `--no-eval` flag is implictly added by the Docker/OCI `--compat` mode.
> 
> Also adds test cases that cover this new functionality, the historic behavior, and general handling of CMD / ENTRYPOINT/ CMD+ENTRYPOINT handling and overrides in Docker/OCI images. This should help us a lot in catching any changes to the 'historic' behaviour, that has been modified inadvertently in the past.
> 
> There is no change to the historic behavior of Singularity (run without `--no-eval` or `--compat`) at this time. OCI / Docker compatible handling by default may be considered for a future release.

2022-05-06 13:49 UTC, DrDaveD commented on e2e/env/env.go
>  		"issue 5426":               c.issue5426, // https://github.com/hpcng/issues/5426
While here, change the comments on these two issues from `hpcng` to `apptainer/singularity`.

2022-05-06 13:51 UTC, DrDaveD commented on internal/pkg/build/sources/conveyorPacker_oci.go
> +if [ -n "$APPTAINER_NO_EVAL" ]; then
add `|| [ -n "$SINGULARITY_NO_EVAL" ]`

2022-05-06 13:54 UTC, DrDaveD commented on internal/pkg/build/sources/conveyorPacker_oci.go
> +eval "set ${SINGULARITY_OCI_RUN}"
Change SINGULARITY_OCI_RUN to APPTAINER_OCI_RUN

2022-05-09 16:12 UTC, edytuk commented
Changes were made according to your comments

2022-05-09 17:10 UTC, DrDaveD requested changes
I'm sorry, I asked for the wrong things on my previous review.  I didn't realize before that the script file was actually going into the container image.  The container image has to stay completely backward compatible, meaning that we only refer to SINGULARITY there, not APPTAINER.   So please go ahead and change back all the APPTAINER_OCI_RUN to SINGULARITY_OCI_RUN, and remove the extra case checking $APPTAINER_NO_EVAL.  I checked and found out that apptainer is indeed setting SINGULARITY_NO_EVAL with the `--no-eval` option.  It is also setting APPTAINER_NO_EVAL but we can't rely on that because we want containers created by apptainer to still run under singularity.

2022-05-10 12:10 UTC, edytuk commented
I changed back all the APPTAINER_OCI_RUN to SINGULARITY_OCI_RUN, and remove the extra case checking $APPTAINER_NO_EVAL

2022-05-10 18:14 UTC, DrDaveD approved these changes

2022-05-11 10:56 UTC, closed without merging